//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1460353.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class danhmuc
    {
        public int id { get; set; }
        public string ten { get; set; }
        public Nullable<int> trinhtrang { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public Nullable<System.DateTime> ngaycapnhat { get; set; }
    }
}
