//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1460353.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class daugiaEntities : DbContext
    {
        public daugiaEntities()
            : base("name=daugiaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<binhluan> binhluans { get; set; }
        public virtual DbSet<chinhsuachitietsp> chinhsuachitietsps { get; set; }
        public virtual DbSet<chitietdanhgia> chitietdanhgias { get; set; }
        public virtual DbSet<danhgia> danhgias { get; set; }
        public virtual DbSet<danhmuc> danhmucs { get; set; }
        public virtual DbSet<kichnguoidung> kichnguoidungs { get; set; }
        public virtual DbSet<lichsudau> lichsudaus { get; set; }
        public virtual DbSet<nguoidung> nguoidungs { get; set; }
        public virtual DbSet<sanpham> sanphams { get; set; }
        public virtual DbSet<thongbao> thongbaos { get; set; }
        public virtual DbSet<yeuthich> yeuthiches { get; set; }
        public virtual DbSet<yeucau> yeucaus { get; set; }
    }
}
