//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1460353.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nguoidung
    {
        public int id { get; set; }
        public string ten { get; set; }
        public string email { get; set; }
        public string username { get; set; }
        public string pass { get; set; }
        public string diachi { get; set; }
        public string sodienthoai { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string gioitinh { get; set; }
        public string anhdaidien { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public Nullable<System.DateTime> ngaycapnhat { get; set; }
        public Nullable<decimal> taikhoan { get; set; }
        public Nullable<int> diem { get; set; }
        public Nullable<int> quyen { get; set; }
        public Nullable<int> tinhtrang { get; set; }
        public Nullable<int> capphep { get; set; }

       
    }
}
