//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1460353.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanpham
    {
        public int id { get; set; }
        public Nullable<int> id_danhmuc { get; set; }
        public Nullable<int> id_nguoidung { get; set; }
        public string ten { get; set; }
        public Nullable<int> soluong { get; set; }
        public string chitiet { get; set; }
        public Nullable<decimal> giakhoidiem { get; set; }
        public Nullable<decimal> giahientai { get; set; }
        public Nullable<int> diemduocdau { get; set; }
        public Nullable<int> id_nguoidunghientai { get; set; }
        public Nullable<System.DateTime> ngaybatdau { get; set; }
        public Nullable<System.DateTime> ngayketthuc { get; set; }
        public Nullable<int> id_danhgia { get; set; }
        public Nullable<int> tinhtrang { get; set; }
        public Nullable<decimal> giacaonhat { get; set; }
        public Nullable<decimal> giamuangay { get; set; }
        public Nullable<int> tang10phut { get; set; }
        public Nullable<int> solantang10phut { get; set; }
        public string mieutangan { get; set; }
        public Nullable<int> luotview { get; set; }
        public Nullable<decimal> giabanmongmuon { get; set; }
    }
}
